# -*- coding: utf-8 -*-
"""rental_fraud_locall.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhHM8cxRL_bhi-G7v7fGlLF89uI1Mqvk

# **설정 단계**
# 1. 시각화 자료에서 한글 적용을 위해 폰트 설치
"""

# 단계 1: 폰트 설치
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

!apt-get -qq -y install fonts-nanum > /dev/null

fe = fm.FontEntry(
    fname=r'/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf', # ttf 파일이 저장되어 있는 경로
    name='NanumGothic')                        # 이 폰트의 원하는 이름 설정
fm.fontManager.ttflist.insert(0, fe)              # Matplotlib에 폰트 추가
plt.rcParams.update({'font.size': 18, 'font.family': 'NanumGothic'})

"""# 2. 폰트 적용을 위한 런타임 재시작 후 한글 폰트 설정"""

# 런타임 재시작
import os
os.kill(os.getpid(), 9)

# 한글 폰트 설정
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm

# 마이너스 표시 문제
mpl.rcParams['axes.unicode_minus'] = False

# 한글 폰트 설정
fe = fm.FontEntry(
    fname=r'/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf', # ttf 파일이 저장되어 있는 경로
    name='NanumGothic')                        # 이 폰트의 원하는 이름 설정
fm.fontManager.ttflist.insert(0, fe)              # Matplotlib에 폰트 추가
plt.rcParams.update({'font.size': 18, 'font.family': 'NanumGothic'}) # 폰트

"""# **전처리 단계**
# 1. 데이터 전처리 작업 및 데이터프레임 형성

# 1-1. 인천시 데이터 전처리 작업
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import seaborn as sns

## 인천 데이터프레임 ##
idf1 = pd.read_csv('/content/drive/MyDrive/big_data/incheon.csv', encoding='cp949')
# 1. 변환 전 기존 데이터 출력
print(idf1.head(), '\n')
# 2. 문자열 데이터를 간략히 하여 정수형 데이터로 입력
idf1['연도'] = idf1['기간'].str.split('~').str[0].str.split('-').str[0].astype(int)
# 3. 불필요한 데이터 삭제
idf1.drop(['기간', '연령별', '연령별_건수'], axis=1, inplace=True)
# 4. 열 이름 재설정
idf1.columns = ['구별', '발생_건수', '연도']
# 5. idf1을 idf2로 복제
idf2 = idf1[:]
# 6 최종 변환 데이터 출력
print(idf2.head())

"""# 1-2. 부산시 데이터 전처리 작업"""

## 부산 데이터프레임 ##
bdf1 = pd.read_csv('/content/drive/MyDrive/big_data/busan.csv', encoding='cp949')
# 1. 변환 전 기존 데이터 출력
print(bdf1.head(),'\n')
# 2. 열 이름 중, 연도에서 '년'을 제거한 정수형 데이터 입력
bdf1.columns = ['구별', 2023, 2024, 2025]
# 3. '구별'을 인덱스로 설정
bdf2 = bdf1.set_index('구별')
# 4. stack 함수를 사용하여 시각화하기 편한 자료로 변형
bdf3 = bdf2.stack().reset_index()
# 5. 열 이름 재설정
bdf3.columns = ['구별', '연도', '발생_건수']
# 6. 최종 변환 데이터 출력
print(bdf3.head())

"""# 1-3. 광주시 데이터 전처리 작업"""

## 광주 데이터프레임 ##
gdf1 = pd.read_csv('/content/drive/MyDrive/big_data/gwangju.csv', encoding='cp949')
# 1. 변환 전 기존 데이터 출력
print(gdf1.head(),'\n')
# 2. '연도'를 인덱스로 설정
gdf2 = gdf1.set_index('연도')
# 3. stack 함수를 사용하여 시각화하기 편한 자료로 변형
gdf3 = gdf2.stack().reset_index()
# 4. 열 이름 재설정
gdf3.columns = ['연도', '구별', '발생_건수']
# 5. 최종 변환 데이터 출력
print(gdf3.head())

"""# 1-4. 울산시 데이터 전처리 작업"""

## 울산 데이터프레임 ##
udf1 = pd.read_csv('/content/drive/MyDrive/big_data/ulsan.csv', encoding='cp949')
# 1. 변환 전 기존 데이터 출력
print(udf1.head(),'\n')
# 2. 열 이름 중, 연도에서 '년'을 제거한 정수형 데이터 입력
udf1.columns = ['구별', 2023, 2024, 2025]
# 3. '연도'를 인덱스로 설정
udf2 = udf1.set_index('구별')
# 4. stack 함수를 사용하여 시각화하기 편한 자료로 변형
udf3 = udf2.stack().reset_index()
# 5. 열 이름 재설정
udf3.columns = ['구별', '연도', '발생_건수']
# 6. 최종 변환 데이터 출력
print(udf3.head())

"""# **시각화 단계**
# 1. 시각화 작업(광역시별)
"""

# 1. 그래프 사이즈 설정
fig=plt.figure(figsize=(50,20))
# 2. 그래프가 배치될 위치 설정
ax1=fig.add_subplot(2,2,1)
ax2=fig.add_subplot(2,2,2)
ax3=fig.add_subplot(2,2,3)
ax4=fig.add_subplot(2,2,4)

# 3. 시각화 자료 표현 방식 설정
sns.set_style('white')
plt.rc('font', family='NanumGothic')
plt.rcParams['axes.unicode_minus'] = False

## sns.barplot을 사용하여 시각화 ##
# 인천 #
sns.barplot(data=idf2, x='구별', y='발생_건수', hue='연도', palette='tab20c', ax=ax1)
ax1.set_title('인천시 전세사기 [군구별]')
# 부산 #
sns.barplot(data=bdf3, x='구별',  y ='발생_건수', hue='연도', palette='PuRd', ax=ax2)
ax2.set_title('부산시 전세사기 [군구별]')
# 광주 #
sns.barplot(data=gdf3, x='구별',  y ='발생_건수', hue='연도', palette='muted', ax=ax3)
ax3.set_title('광주시 전세사기 [군구별]')
# 울산 #
sns.barplot(data=udf3, x='구별',  y ='발생_건수', hue='연도', palette='PuBuGn', ax=ax4)
ax4.set_title('울산시 전세사기 [군구별]')

plt.tight_layout()
plt.show()

"""# 2. 시각화 작업(전국)"""

# 1. 각 데이터 프레임에 '도시'열 추가
idf2['도시'] = '인천'
bdf3['도시'] = '부산'
gdf3['도시'] = '광주'
udf3['도시'] = '울산'

# 2. 네 도시의 데이터를 하나로 총합
df_all = pd.concat([idf2, bdf3, gdf3, udf3], ignore_index=True)

# 3. 그래프 사이즈 설정
plt.figure(figsize=(15, 6))

# 4. 그래프의 x, y 좌표 값을 설정해주고 범주형 데이터로 '도시'열을 선택
sns.lineplot(x='연도', y='발생_건수', hue='도시', data=df_all, marker='o')

plt.xticks([2023, 2024, 2025], labels=['2023', '2024', '2025'])
plt.title('도시별 연도에 따른 전세사기 발생 건수 변화 추이')
plt.xlabel('연도')
plt.ylabel('발생 건수')
plt.grid(True)
plt.show()

"""# **머신러닝 단계**

# 데이터를 학습시켜 앞으로의 결과를 예측(인천)
"""

## 인천 데이터 | 학습을 위해 데이터 타입 변환 ##
idf2['연도'] = idf2['연도'].astype(int)
idf2['발생_건수'] = idf2['발생_건수'].astype(float)

# 1. 연도(X)에 따른 발생_건수(y)
X = idf2[['연도']]
y = idf2['발생_건수']

# 2. train/test 분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0)

# 3. 선형회귀 모델 학습
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

# 4. 모델 평가
print("훈련 점수 :", model.score(X_train, y_train))
print("테스트 점수:", model.score(X_test, y_test))

# 5. 향후 연도 예측
future_years = pd.DataFrame({'연도': [2026, 2027, 2028]})
future_pred = model.predict(future_years)

print("\n=== 인천 미래 발생 건수 예측 ===")
for y, p in zip(future_years['연도'], future_pred):
    print(f"{y}년 예상 발생 건수: {p:.1f} 건")

# 6. 시각화 (실제 데이터 + 회귀선)
plt.figure(figsize=(10,6))

# 실제 데이터 산점도
plt.scatter(idf2['연도'], idf2['발생_건수'], label='실제 데이터')

# 회귀선
years_line = np.array(range(idf2['연도'].min(), 2029)).reshape(-1,1)
pred_line = model.predict(years_line)
plt.plot(years_line, pred_line, color='red', label='회귀선')

plt.xlabel('연도')
plt.ylabel('발생 건수')
plt.title('인천 발생 건수 회귀 예측')
plt.legend()
plt.show()